from algorithms.fcfs import FCFS
from algorithms.non_preemptive_sjf import NonPreemptiveSJF
from algorithms.preemptive_sjf import PreemptiveSJF
from algorithms.non_preemptive_priority import NonPreemptivePriority
from algorithms.preemptive_priority import PreemptivePriority
from algorithms.rr import RR